databases:
  - name: music-sorterdb
    plan: free
    databaseName: music-sorter
    user: music-sorter

services:
  - type: web
    plan: free
    name: music-sorter
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn music-sorter.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: music-sorterdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4