# Generated by Django 5.1.1 on 2024-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='music_files/')),
                ('track_name', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
